[package]
name = "salt"
version = "0.1.0"
authors = ["Caleb Rutland"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.1" }
legion = { version = "0.4.0" }
